name: Bot Pantau Emas

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  eksekusi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Jalankan Skrip Update
        run: node update_gold.js

      - name: Simpan Perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add harga_emas.csv
          git commit -m "Update harga emas harian [skip ci]" || exit 0
          git push